=== whitten/MOCHA/etc/xml/schema/drugInfoSchemaOutput.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response"
    targetNamespace="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xsd:element name="drugInfoResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="drugsNotFound"
                    minOccurs="0" />
                <xsd:element
                    ref="drug"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="drug">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="routes"
                    minOccurs="0" />
                <xsd:element
                    ref="doseTypes"
                    minOccurs="0" />
                <xsd:element
                    name="strengthUnit"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute
                name="gcnSeqNo"
                type="xsd:integer"
                use="required" />
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="routes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="route"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="route">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="id"
                    type="xsd:string" />
                <xsd:element
                    name="name"
                    type="xsd:string" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="doseTypes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="doseType"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="doseType">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="id"
                    type="xsd:string" />
                <xsd:element
                    name="name"
                    type="xsd:string" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="drugsNotFound">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="drugNotFound"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="drugNotFound">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="drug" />
            </xsd:sequence>
            <xsd:attribute
                name="status"
                type="notFoundStatus" />
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="notFoundStatus">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="UnableToLoadDrugForGcnSeqNo" />
        </xsd:restriction>
    </xsd:simpleType>

=== whitten/MOCHA/etc/xml/test/messages/atp/5101Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<drugInfoResponse
    xsi:schemaLocation="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response drugInfoSchemaOutput.xsd"
    xmlns="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <drug gcnSeqNo="60301">
        <routes>
            <route>
                <id>006</id>
                <name>CONTINUOUS INFUSION</name>
            </route>
            <route>
                <id>052</id>
                <name>INTRAVENOUS</name>
            </route>
            <route>
                <id>079</id>
                <name>SUBCUTANEOUS</name>
            </route>
        </routes>
        <doseTypes>
            <doseType>
                <id>01</id>
                <name>LOADING</name>
            </doseType>
            <doseType>
                <id>02</id>
                <name>MAINTENANCE</name>
            </doseType>
            <doseType>
                <id>07</id>
                <name>SINGLE DOSE</name>
            </doseType>
        </doseTypes>
        <strengthUnit>UNIT/250 ML</strengthUnit>
    </drug>
    <drug gcnSeqNo="16579">
        <routes>
            <route>
                <id>064</id>
                <name>ORAL</name>
            </route>
        </routes>
        <doseTypes>
            <doseType>
                <id>02</id>
                <name>MAINTENANCE</name>
            </doseType>
            <doseType>
                <id>07</id>
                <name>SINGLE DOSE</name>
            </doseType>
            <doseType>
                <id>08</id>
                <name>INITIAL DOSE</name>
            </doseType>
        </doseTypes>
        <strengthUnit>MG</strengthUnit>
    </drug>

=== whitten/MOCHA/etc/xml/test/messages/drugInfoSingleResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<drugInfoResponse
    xsi:schemaLocation="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response drugInfoSchemaOutput.xsd"
    xmlns="ext/domain/pharmacy/peps/external/common/preencapsulation/vo/drug/info/response"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <drug gcnSeqNo="266">
        <routes>
            <route>
                <id>064</id>
                <name>ORAL</name>
            </route>
        </routes>
        <doseTypes>
            <doseType>
                <id>01</id>
                <name>LOADING</name>
            </doseType>
            <doseType>
                <id>02</id>
                <name>MAINTENANCE</name>
            </doseType>
            <doseType>
                <id>07</id>
                <name>SINGLE DOSE</name>
            </doseType>
            <doseType>
                <id>08</id>
                <name>INITIAL DOSE</name>
            </doseType>
            <doseType>
                <id>09</id>
                <name>INTERMEDIATE DOSE</name>
            </doseType>
        </doseTypes>
        <strengthUnit>MG</strengthUnit>
    </drug>
